name = "AtmosphericTurbulenceSimulator"
uuid = "b10e1436-1925-4c36-93d0-25dc9f56f811"
version = "0.1.0"
authors = ["aryavorskiy <aleksandr.iavorskii@weizmann.ac.il>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "0.25"
FFTW = "1"
HDF5 = "0.17"
LinearAlgebra = "1.12"
ProgressMeter = "1.11.0"
Random = "1.11"
SparseArrays = "1.12.0"
